package com.alanlapierre.solarsystem.calculator;

public enum PositionName{
	POSITIONS_ALIGNED_BETWEEN_THEM_AND_POSITION_ZERO,
	POSITIONS_ALIGNED_BETWEEN_THEM,
	POSITION_ZERO_INSIDE_TRIANGLE,
	POSITION_ZERO_OUTSIDE_TRIANGLE
}
	

